### ISSUE TITLE
show MDA file handling in config

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/tiled-template#1]
Add this line: https://github.com/prjemian/tiled-demo/blob/f25b9c182ae3d42d5f0dc54cb60585383d3c9d88/config.yml#L33 and this line: https://github.com/prjemian/tiled-demo/blob/f25b9c182ae3d42d5f0dc54cb60585383d3c9d88/config.yml#L39

as in:

```yml
      mimetypes_by_file_ext:
        .mda: application/x-mda
      readers_by_mimetype:
        application/x-mda: synApps_mda:read_mda
```
